# Generated by Django 4.1.4 on 2022-12-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioResearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='maintheme',
            name='theme',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='maintheme',
            name='main_theme',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='main_theme',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='newpaper',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='newpaper',
            name='main_theme',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='searchpaper',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='searchpaper',
            name='main_theme',
            field=models.TextField(default=''),
        ),
    ]
