# Generated by Django 4.1.4 on 2022-12-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioResearch', '0003_alter_paper_main_theme_alter_paper_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintheme',
            name='main_theme',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newpaper',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='searchpaper',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
